version: "3"
services:
  nodejs:
    container_name: node-api
    ports:
      - "49160:8080"
    build: .
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - PORT=8080
    volumes:
      - ./:/usr/node/node-docker/
  es-head:
    container_name: node-elasticsearch-head
    ports:
      - "9100:9100"
    build:
      context: .
      dockerfile: ./Dockerfile.es.head
  kibana:
    image: kibana:7.12.0
    container_name: node-kibana
    ports:
      - "5601:5601"
    restart: "always"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  elasticsearch:
    container_name: node-elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile.es
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
      - ./esData:/usr/share/elasticsearch/data