FROM node:14.16.0

WORKDIR /usr/es-head

RUN npm config set registry https://registry.npm.taobao.org

RUN git clone git://github.com/mobz/elasticsearch-head.git

RUN cp -R elasticsearch-head/. .

RUN npm install

EXPOSE 9100

CMD ["npm", "start"]